services:
  postgres:
    image: postgres:17-bullseye
    container_name: sm-postgres
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sm-backend
    command: node ace serve --watch
    develop:
      watch:
        - action: sync
          path : .
          target: /home/node/app
          ignore:
            - node_modules/
            - .git
            - Dockerfile
            - docker-compose.yaml
            - package-lock.json
            - package.json
            - .gitignore
            - .editorconfig
            - .env.example
            - .md
            - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_PORT: ${PG_PORT}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      TZ: ${TZ}
    env_file:
      - ./.env

volumes:
  postgres-data:
